/**
 * The RSS feed, as a string.
 *
 * Production serves a live feed at `/feed` AND `/feed.xml` on all three
 * origins, generated by jekyll-feed. The migrated build emitted neither, and
 * that is the quietest possible regression: a reader whose feed stops updating
 * produces no 404 in any log and no complaint. They simply stop hearing from
 * you. `routes/policy.json` had all six URLs as `dropKind: unresolved`.
 *
 * Hand-written rather than `@astrojs/rss` because the XML is forty lines and a
 * dependency is forever. The one thing worth borrowing from a library — correct
 * escaping — is here explicitly.
 *
 * Both `/feed` and `/feed.xml` serve this identical document, because
 * production serves both and a subscriber's saved URL could be either.
 */

/**
 * XML text escaping.
 *
 * `&` first, always: escaping it after `<` would turn `&lt;` into `&amp;lt;`.
 * That ordering bug is the reason this is a named function rather than a chain
 * inlined at three call sites.
 */
export const xmlEscape = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** RFC-822, which is what RSS 2.0 requires — not ISO-8601. */
export function rfc822(iso) {
  const d = new Date(`${String(iso).slice(0, 10)}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return null;
  return d.toUTCString();
}

/**
 * Build the feed document.
 *
 * `items` are page records; only dated ones can appear, because an RSS item
 * without a `pubDate` sorts unpredictably in every reader. Language is
 * per-item, since the Lab publishes in English and Spanish and a reader that
 * knows which is which can filter.
 */
export function renderFeed({ origin, title, description, items, buildDate }) {
  const entries = items
    .filter((p) => p.data.date)
    .sort((a, b) => String(b.data.date).localeCompare(String(a.data.date)))
    .map((p) => {
      const url = `${origin}/${p.data.outputPath}.html`;
      const date = rfc822(p.data.date);
      return [
        '    <item>',
        `      <title>${xmlEscape(p.data.indexLabel ?? p.data.title)}</title>`,
        `      <link>${xmlEscape(url)}</link>`,
        // Stable and unique, and not a URL a reader should follow — that is
        // what isPermaLink="false" says. It stays stable if the title changes.
        `      <guid isPermaLink="false">${xmlEscape(p.data.outputPath)}</guid>`,
        date ? `      <pubDate>${date}</pubDate>` : null,
        p.data.lang ? `      <dc:language>${xmlEscape(p.data.lang)}</dc:language>` : null,
        p.data.description ? `      <description>${xmlEscape(p.data.description)}</description>` : null,
        '    </item>',
      ]
        .filter(Boolean)
        .join('\n');
    });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">',
    '  <channel>',
    `    <title>${xmlEscape(title)}</title>`,
    `    <link>${xmlEscape(origin)}/</link>`,
    `    <description>${xmlEscape(description)}</description>`,
    // Self-reference, which every validator wants and jekyll-feed emitted.
    `    <atom:link href="${xmlEscape(origin)}/feed.xml" rel="self" type="application/rss+xml" />`,
    buildDate ? `    <lastBuildDate>${buildDate}</lastBuildDate>` : null,
    ...entries,
    '  </channel>',
    '</rss>',
    '',
  ]
    .filter(Boolean)
    .join('\n');
}
