/**
 * Flattens the site's stylesheets into one file for the design-sync converter.
 *
 * Why this exists: the converter appends `cfg.cssEntry` verbatim, so an entry
 * made of `@import '../src/styles/*.css'` ships those paths unresolved and
 * every design renders unstyled. It needs a real, already-flat stylesheet.
 *
 * The order is read out of `BaseLayout.astro` rather than listed here. That
 * order IS the design system's cascade, and a copy of it would rot the first
 * time a stylesheet is added to the layout and not to this script. If the
 * layout stops importing its stylesheets one-per-line, this throws rather than
 * silently shipping a partial system.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, '..');
const layout = join(pkgRoot, 'src/layouts/BaseLayout.astro');
const outFile = join(here, '.cache/styles-flat.css');

const src = readFileSync(layout, 'utf8');
const order = [...src.matchAll(/^import\s+'\.\.\/styles\/([\w-]+\.css)';$/gm)].map((m) => m[1]);

if (order.length === 0) {
  throw new Error(`no '../styles/*.css' imports found in ${layout} — the import shape changed`);
}

const chunks = [
  `/* Generated by .design-sync/build-styles.mjs — do not edit.\n` +
    `   Source order: src/layouts/BaseLayout.astro (${order.length} stylesheets). */\n`,
];

for (const name of order) {
  const p = join(pkgRoot, 'src/styles', name);
  if (!existsSync(p)) throw new Error(`BaseLayout imports styles/${name} but it does not exist`);
  chunks.push(`\n/* ── src/styles/${name} ─────────────────────────────── */\n`);
  chunks.push(readFileSync(p, 'utf8'));
}

// Last, so it outranks anything the stylesheets above leave ambiguous. See the
// file's own header for why the design host makes this necessary.
chunks.push(`\n/* ── .design-sync/surface.css ───────────────────────────── */\n`);
chunks.push(readFileSync(join(here, 'surface.css'), 'utf8'));

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, chunks.join(''));
console.error(`styles-flat.css: ${order.length} stylesheets → ${(chunks.join('').length / 1024) | 0} KB`);
console.error(`  order: ${order.join(' → ')}`);
