#!/usr/bin/env node
/**
 * verify:a11y — the accessibility and responsive gates of MW-11, as assertions.
 *
 * MW-11 lists "keyboard navigation across every interactive element", "visible
 * focus states in every context", "heading hierarchy and landmarks correct",
 * "contrast meets WCAG 2.2 AA", "prefers-reduced-motion honoured" and "long
 * Spanish copy and unbroken URLs wrap safely" under *human* review gates, and
 * they do need a human eye. But a human reviewing 133 pages once, by hand, at a
 * single point in time, is not a gate — it is a snapshot. The next migration run
 * regenerates every body from the legacy checkouts and nothing would notice if a
 * heading level, an iframe title or an image alt went missing again.
 *
 * So the mechanical half is asserted here and runs on every build. What is left
 * for the human is what genuinely needs judgement: whether an alt text is a good
 * description, whether a focus ring is legible against a photograph, whether the
 * reading order makes sense. This check does not claim to be that review, and
 * the ledger records the human gates separately.
 *
 * Everything is measured against dist/ — what actually ships — and against the
 * built CSS rather than the sources, so a rule that the bundler dropped cannot
 * pass by existing in src/.
 *
 * WHAT THIS DELIBERATELY DOES NOT DO: it does not run a headless browser and it
 * does not compute layout. Horizontal overflow at 360/768/1024/1440 CSS px is a
 * layout question, and it was measured in a real browser at MW-11 sign-off; the
 * ledger entry `MW-11 a11y/responsive-sweep` records the numbers. The static
 * proxies for it here (a zoomable viewport, media bounded to its container,
 * wide content in its own scroll container, unbroken strings allowed to break)
 * are what a build can honestly assert without one.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { runStandalone } from './lib/report.mjs';
import { ARTIFACTS, indexDist } from './lib/artifacts.mjs';
import { readableText, mainOf } from './lib/html-text.mjs';

// ── html helpers ──────────────────────────────────────────────────────────

/**
 * Attributes of a single start tag.
 *
 * Deliberately not a parser. Every page in this build is generated by Astro
 * from content the migration normalised, so the tag soup a real parser exists to
 * survive is not present — and a dependency-free check is one that still runs in
 * five years. Boolean attributes are recorded as ''.
 */
export function attrsOf(tag) {
  const out = {};
  for (const m of tag.matchAll(/([a-zA-Z:_-][\w:.-]*)\s*=\s*("([^"]*)"|'([^']*)'|([^\s>]+))/g)) {
    out[m[1].toLowerCase()] = m[3] ?? m[4] ?? m[5] ?? '';
  }
  for (const m of tag.matchAll(/(?:\s)([a-zA-Z:_-][\w:.-]*)(?=[\s>]|\/>|$)/g)) {
    const k = m[1].toLowerCase();
    if (!(k in out)) out[k] = '';
  }
  return out;
}

/** Text a reader would hear. The one form that decodes entities properly. */
export const textOf = readableText;

/* The shell owns <main>; page content is what is inside it. mainOf is shared
   with verify:content, which had its own copy under a different name. */

/**
 * Whether an element is hidden from assistive technology.
 *
 * `aria-hidden="true"` with `tabindex="-1"` is how the index list's decorative
 * cover thumbnail is expressed: the anchor beside it carries the same
 * destination and the readable name, so a second announcement of the same link
 * would be noise. Removed from the tree AND from the tab order is a complete
 * removal; either one alone would not be, and this asserts both.
 */
const isHiddenFromAT = (a) => a['aria-hidden'] === 'true' || 'hidden' in a;

/**
 * The character ranges covered by an `aria-hidden="true"` subtree.
 *
 * `aria-hidden` is inherited, so the attribute on the element itself is only
 * half the question. Mailchimp's bot honeypot is the case that proves it: a
 * bare `<input name="b_…">` with no label at all, which is correct — it sits
 * inside `<div style="left:-5000px" aria-hidden="true">` and carries
 * `tabindex="-1"`, so no reader announces it and no keyboard reaches it.
 * Labelling it would be worse than not, and a check that demanded a label there
 * would be demanding a defect.
 *
 * Matching is by tag nesting from the opening tag; a subtree that never closes
 * runs to the end of the document, which is the conservative direction — it
 * suppresses findings rather than inventing them, and any focusable element
 * inside it is still asserted by `hidden-focusable`.
 *
 * Each range records whether it is also *unfocusable*. `aria-hidden` alone
 * removes an element from the accessibility tree but leaves it in the tab
 * order, which is the worst of both — a keyboard user lands on something no
 * reader will announce. `display:none`, `visibility:hidden` and the `hidden`
 * attribute remove it from both, so a region carrying one of those needs no
 * `tabindex="-1"` on the things inside it. The legacy `.pdf-fallback` block is
 * exactly this shape and is correct as it stands.
 */
export function hiddenRanges(html) {
  const ranges = [];
  for (const open of html.matchAll(/<([a-z][\w-]*)\b[^>]*\baria-hidden\s*=\s*["']true["'][^>]*>/gi)) {
    const tag = open[1].toLowerCase();
    if (/^(img|input|br|hr|meta|link|source|track|area|col|embed|param|wbr|base)$/.test(tag)) continue;
    if (open[0].endsWith('/>')) continue;
    const a = attrsOf(open[0]);
    const unfocusable =
      'hidden' in a || /display\s*:\s*none|visibility\s*:\s*hidden/i.test(a.style || '');
    let depth = 1;
    const nested = new RegExp(`<(/?)${tag}\\b[^>]*>`, 'gi');
    nested.lastIndex = open.index + open[0].length;
    let m;
    while ((m = nested.exec(html))) {
      depth += m[1] ? -1 : 1;
      if (depth === 0) break;
    }
    ranges.push({ start: open.index, end: m ? m.index + m[0].length : html.length, unfocusable });
  }
  return ranges;
}

const rangeAt = (ranges, index) => ranges.find((r) => index >= r.start && index < r.end) || null;

// ── one page ──────────────────────────────────────────────────────────────

/**
 * Every accessibility problem on one page.
 *
 * Returns a flat list of `{kind, detail}` so the report can group by kind and
 * name the worst offenders, rather than printing 133 pages of noise.
 */
export function auditPage(url, html) {
  const problems = [];
  const bad = (kind, detail) => problems.push({ kind, detail: `${url}: ${detail}` });
  const main = mainOf(html);
  const hidden = hiddenRanges(main);
  /**
   * Whether a control is hidden, and whether being hidden also took it out of
   * the tab order. `keepsTabStop` is the reportable half: hidden from readers
   * but still reachable by keyboard.
   */
  const hiddenState = (a, index) => {
    const range = rangeAt(hidden, index);
    const own = isHiddenFromAT(a);
    if (!range && !own) return { hidden: false, keepsTabStop: false };
    const unfocusable = (range && range.unfocusable) || 'hidden' in a;
    return { hidden: true, keepsTabStop: !unfocusable && a.tabindex !== '-1' };
  };

  // ---- document -----------------------------------------------------------
  const htmlTag = /<html\b[^>]*>/i.exec(html);
  const lang = htmlTag ? (attrsOf(htmlTag[0]).lang || '').trim() : '';
  if (!lang) bad('lang', 'no lang on <html> — a screen reader reads it with the wrong phonemes');

  const viewport = /<meta\b[^>]*name=["']viewport["'][^>]*>/i.exec(html);
  if (!viewport) {
    bad('viewport', 'no viewport meta — the page renders at desktop width on a phone');
  } else {
    const content = attrsOf(viewport[0]).content || '';
    if (/user-scalable\s*=\s*(no|0)/i.test(content)) bad('viewport', 'viewport disables pinch zoom');
    const maxScale = /maximum-scale\s*=\s*([\d.]+)/i.exec(content);
    if (maxScale && Number(maxScale[1]) < 2) bad('viewport', `viewport caps zoom at ${maxScale[1]}×`);
  }

  /**
   * A page that meta-refreshes elsewhere is a redirect, not a document. It has
   * no outline to get right and holding it to one would force a heading nobody
   * reads onto a page nobody sees. `/interplanetary-players` is the only one.
   */
  const isRedirectStub = /<meta\b[^>]*http-equiv=["']refresh["']/i.test(html);

  // ---- heading outline ----------------------------------------------------
  const headings = [...main.matchAll(/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi)].map((m) => ({
    level: Number(m[1]),
    text: textOf(m[2]),
  }));

  const h1s = headings.filter((h) => h.level === 1);
  if (!isRedirectStub && h1s.length !== 1) {
    bad(
      'h1',
      h1s.length === 0
        ? 'no <h1> — the page has no name in the heading outline'
        : `${h1s.length} <h1> elements (${h1s.map((h) => JSON.stringify(h.text.slice(0, 40))).join(', ')})`,
    );
  }

  let previous = 0;
  for (const h of headings) {
    if (previous && h.level > previous + 1) {
      bad('heading-skip', `h${previous} → h${h.level} at ${JSON.stringify(h.text.slice(0, 40))}`);
      break;
    }
    previous = h.level;
  }

  // ---- images and frames --------------------------------------------------
  for (const m of main.matchAll(/<img\b[^>]*>/gi)) {
    const a = attrsOf(m[0]);
    if (!('alt' in a)) bad('img-alt', `<img src="${a.src || '?'}"> has no alt attribute`);
  }

  for (const m of html.matchAll(/<iframe\b[^>]*>/gi)) {
    const a = attrsOf(m[0]);
    if (!(a.title || '').trim()) bad('iframe-title', `<iframe src="${a.src || '?'}"> has no title`);
  }

  // ---- interactive elements ----------------------------------------------
  /**
   * An accessible name, computed the way the accname spec resolves one for a
   * link or a button: aria-labelledby, then aria-label, then the element's own
   * contents (including any `alt` on an image inside it and any `<title>` on an
   * inline `<svg>`), then the `title` attribute as the last resort.
   */
  const nameOf = (a, inner) => {
    if ((a['aria-labelledby'] || '').trim()) return 'aria-labelledby';
    if ((a['aria-label'] || '').trim()) return 'aria-label';
    if (textOf(inner)) return 'contents';
    for (const img of inner.matchAll(/<img\b[^>]*>/gi)) if ((attrsOf(img[0]).alt || '').trim()) return 'image alt';
    const svgTitle = /<svg[\s\S]*?<title\b[^>]*>([\s\S]*?)<\/title>/i.exec(inner);
    if (svgTitle && textOf(svgTitle[1])) return 'svg title';
    if ((a.title || '').trim()) return 'title attribute';
    return null;
  };

  for (const m of main.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)) {
    const a = attrsOf(`<a${m[1]}>`);
    if (!('href' in a)) continue; // an anchor without href is not a link
    const state = hiddenState(a, m.index);
    if (state.hidden) {
      if (state.keepsTabStop) bad('hidden-focusable', `aria-hidden link to ${a.href} is still in the tab order`);
      continue;
    }
    const name = nameOf(a, m[2]);
    if (!name) bad('link-name', `<a href="${a.href}"> has no accessible name`);
    /**
     * A link whose only name is its `title` attribute is a link with nothing in
     * it. It computes a name, so it is not strictly nameless — and it is also
     * invisible, zero-size, unreachable by touch and unannounced by anything
     * that does not surface `title`. Both facts are true; this reports it.
     */
    else if (name === 'title attribute') bad('empty-link', `<a href="${a.href}"> is empty — named only by title`);
  }

  for (const m of main.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/gi)) {
    const a = attrsOf(`<button${m[1]}>`);
    if (hiddenState(a, m.index).hidden) continue;
    if (!nameOf(a, m[2])) bad('button-name', '<button> has no accessible name');
  }

  /**
   * `<summary>` is the disclosure's own control. It is a real button to the
   * browser, so it needs a real name, and an empty one leaves the compact
   * navigation operable but unannounced.
   */
  for (const m of main.matchAll(/<summary\b([^>]*)>([\s\S]*?)<\/summary>/gi)) {
    if (!nameOf(attrsOf(`<summary${m[1]}>`), m[2])) bad('button-name', '<summary> has no accessible name');
  }

  // ---- form controls ------------------------------------------------------
  const NOT_LABELLED = new Set(['hidden', 'submit', 'button', 'reset', 'image']);
  /** `<label> Your name: <input> </label>` — the wrapping form of a label. */
  const wrapped = new Set();
  for (const m of html.matchAll(/<label\b[^>]*>([\s\S]*?)<\/label>/gi)) {
    if (!textOf(m[1])) continue;
    for (const c of m[1].matchAll(/<(input|select|textarea)\b[^>]*>/gi)) wrapped.add(c[0]);
  }
  const labelFor = new Set(
    [...html.matchAll(/<label\b[^>]*\bfor=["']([^"']+)["'][^>]*>/gi)].map((m) => m[1]),
  );

  for (const m of main.matchAll(/<(input|select|textarea)\b[^>]*>/gi)) {
    const a = attrsOf(m[0]);
    if (NOT_LABELLED.has((a.type || '').toLowerCase())) continue;
    const state = hiddenState(a, m.index);
    if (state.hidden) {
      if (state.keepsTabStop) {
        bad('hidden-focusable', `<${m[1]} name="${a.name || '?'}"> is aria-hidden but still in the tab order`);
      }
      continue;
    }
    const labelled =
      (a['aria-label'] || '').trim() ||
      (a['aria-labelledby'] || '').trim() ||
      (a.id && labelFor.has(a.id)) ||
      wrapped.has(m[0]);
    if (!labelled) bad('control-label', `<${m[1]} name="${a.name || '?'}"> has no label`);
  }

  // ---- focus order and identity ------------------------------------------
  for (const m of html.matchAll(/\btabindex\s*=\s*["'](\d+)["']/gi)) {
    if (Number(m[1]) > 0) {
      bad('tabindex', `positive tabindex=${m[1]} — it reorders the whole page's tab sequence`);
      break;
    }
  }

  const ids = [...html.matchAll(/\sid\s*=\s*["']([^"']+)["']/gi)].map((m) => m[1]);
  const seen = new Set();
  const duplicated = new Set();
  for (const id of ids) (seen.has(id) ? duplicated.add(id) : seen.add(id));
  if (duplicated.size) bad('duplicate-id', `duplicate id ${[...duplicated].slice(0, 3).map((i) => `#${i}`).join(', ')}`);

  /**
   * A fragment link to an id the page does not carry silently does nothing —
   * and the skip link is the first focusable element on all 133 pages, so if
   * anything here goes stale it is the one that matters most.
   */
  for (const m of html.matchAll(/<a\b[^>]*href\s*=\s*["']#([^"']+)["'][^>]*>/gi)) {
    if (!seen.has(m[1])) bad('dead-fragment', `link to #${m[1]} — no element carries that id`);
  }

  // ---- landmarks ----------------------------------------------------------
  const mains = (html.match(/<main\b/gi) || []).length;
  if (mains !== 1) bad('landmark', `${mains} <main> landmarks — there must be exactly one`);
  if (!/<header\b/i.test(html)) bad('landmark', 'no <header> landmark');
  if (!/<footer\b/i.test(html)) bad('landmark', 'no <footer> landmark');

  const navs = [...html.matchAll(/<nav\b[^>]*>/gi)].map((m) => attrsOf(m[0]));
  if (navs.length > 1) {
    const unnamed = navs.filter((a) => !(a['aria-label'] || '').trim() && !(a['aria-labelledby'] || '').trim());
    if (unnamed.length) bad('nav-name', `${unnamed.length} of ${navs.length} <nav> landmarks are unnamed`);
  }

  // ---- keyboard operability ----------------------------------------------
  /**
   * A control built from a click handler on a non-interactive element cannot be
   * reached by keyboard at all. Nothing on this site should have one — MW-9
   * allows application JavaScript on exactly one page — so this is both an
   * accessibility assertion and a second lock on that rule.
   */
  for (const m of html.matchAll(/\son(click|mousedown|mouseup|mouseover|keypress)\s*=/gi)) {
    bad('inline-handler', `inline on${m[1]} handler — not reachable by keyboard`);
    break;
  }

  // ---- tables -------------------------------------------------------------
  for (const m of main.matchAll(/<table\b([^>]*)>([\s\S]*?)<\/table>/gi)) {
    const a = attrsOf(`<table${m[1]}>`);
    if (a.role === 'presentation' || a.role === 'none') continue;
    if (!/<th\b/i.test(m[2])) {
      bad('table-header', `a <table> has no <th> — its rows are announced without their column`);
    }
  }

  return problems;
}

// ── colour ────────────────────────────────────────────────────────────────

const hexToRgb = (hex) => {
  const h = hex.trim().replace('#', '');
  const full = h.length === 3 ? [...h].map((c) => c + c).join('') : h;
  return [0, 2, 4].map((i) => parseInt(full.slice(i, i + 2), 16));
};

/** WCAG relative luminance. */
export function luminance([r, g, b]) {
  const lin = [r, g, b].map((v) => {
    const s = v / 255;
    return s <= 0.04045 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2];
}

export function contrastRatio(fg, bg) {
  const a = luminance(fg);
  const b = luminance(bg);
  const [hi, lo] = a > b ? [a, b] : [b, a];
  return (hi + 0.05) / (lo + 0.05);
}

/** `color-mix(in srgb, var(--ink) 60%, transparent)` composited over a surface. */
const composite = (fg, alpha, bg) => fg.map((c, i) => alpha * c + (1 - alpha) * bg[i]);

/**
 * Resolve the token values a surface actually renders with, from the built CSS.
 *
 * Reading the built stylesheet rather than src/styles/tokens.css is the whole
 * point: a token the bundler dropped, overrode or mangled would still be correct
 * in the source. Only two forms are supported — a hex literal and the
 * `color-mix(… N%, transparent)` derivation the token file uses — because those
 * are the only two forms the token file is allowed to contain.
 */
export function resolveSurface(css, selector) {
  const block = new RegExp(`${selector}\\s*\\{([^}]*)\\}`).exec(css);
  if (!block) return null;
  const root = /:root\s*\{([^}]*)\}/.exec(css);
  const declarations = `${root ? root[1] : ''};${block[1]}`;

  const raw = new Map();
  for (const m of declarations.matchAll(/(--[\w-]+)\s*:\s*([^;]+)/g)) raw.set(m[1], m[2].trim());

  const resolve = (name, depth = 0) => {
    if (depth > 8) return null;
    const value = raw.get(name);
    if (!value) return null;
    if (/^#[0-9a-f]{3,8}$/i.test(value)) return { rgb: hexToRgb(value), alpha: 1 };
    const varRef = /^var\(\s*(--[\w-]+)\s*\)$/.exec(value);
    if (varRef) return resolve(varRef[1], depth + 1);
    const mix = /^color-mix\(\s*in srgb\s*,\s*var\(\s*(--[\w-]+)\s*\)\s*([\d.]+)%\s*,\s*transparent\s*\)$/i.exec(value);
    if (mix) {
      const base = resolve(mix[1], depth + 1);
      return base ? { rgb: base.rgb, alpha: (Number(mix[2]) / 100) * base.alpha } : null;
    }
    return null;
  };
  return resolve;
}

/**
 * The colour pairs this design actually paints, and the threshold each one owes.
 *
 * WCAG 2.2: 4.5:1 for body text, 3:1 for large text, for user-interface
 * components and for meaningful graphics. `--ink-faint` is listed at 3 rather
 * than 4.5 for a stated reason and not to make a number pass: it colours the
 * `aria-hidden` glyph runs and the Helix diagram's hairlines, and it is used for
 * no text a reader is meant to read. If it is ever put on body copy, that is a
 * change to this table as well as to the stylesheet.
 */
const CONTRAST_PAIRS = [
  { fg: '--ink', bg: '--sf-base', min: 4.5, what: 'body text' },
  { fg: '--ink-muted', bg: '--sf-base', min: 4.5, what: 'muted prose, navigation links' },
  { fg: '--ink-meta', bg: '--sf-base', min: 4.5, what: 'meta lines, captions, copyright' },
  { fg: '--ink-faint', bg: '--sf-base', min: 3, what: 'decorative glyphs and hairlines (never text)', onlyWherePainted: true },
  { fg: '--sf-base', bg: '--action-invert', min: 4.5, what: 'skip link, hover inversion' },
  { fg: '--pigment-ink', bg: '--c-maar', min: 4.5, what: 'type on the maar pastel' },
  { fg: '--pigment-ink', bg: '--c-collect', min: 4.5, what: 'type on the collect pastel' },
  { fg: '--pigment-ink', bg: '--c-tree', min: 4.5, what: 'type on the tree pastel' },
  { fg: '--focus-c', bg: '--sf-base', min: 3, what: 'the focus ring' },
  /**
   * The cut word — `patterns/mark`. It is the one place in the design that puts
   * type on a field which is neither a surface role nor a pastel: the field is
   * `--sf-paper`, the page's own ink used as paper, and the type on it is dark.
   *
   * `--sf-paper` is a constant on both surfaces — it is not swapped by
   * `[data-surface='paper']`, which reads it rather than redefining it — so a
   * cut word is the same clipping on a dark page and on a paper one, and this
   * single pair covers both.
   */
  { fg: '--pigment-ink', bg: '--sf-paper', min: 4.5, what: 'a cut word — dark type on the cream field' },
  /**
   * The stamp's border — `patterns/mark`, mark 4.
   *
   * Listed at 3 and not 4.5 because it is a rule and not type, and WCAG 2.2 asks
   * 3:1 of a meaningful graphic. The stamp's LETTERS are `--ink-meta`, which the
   * meta-line pair above already asserts at 4.5 — 4a draws them in the tree
   * pigment and they do not ship that way, because "a pastel is always a
   * background, never type".
   *
   * The pair is measured per surface, which is the point of it being here at
   * all: `--c-tree` against `--sf-paper` is 1.30:1, so on a paper route the gold
   * rule would be a stamp nobody could see, and `tokens.css` swaps it for the
   * meta ink there. Without this line that swap would be an unverified claim.
   */
  { fg: '--mark-stamp-rule', bg: '--sf-base', min: 3, what: 'the stamp border — a rule, not type' },
];

/**
 * The class names of every CSS rule that paints with a given token.
 *
 * Used by `onlyWherePainted`, which exists for exactly one role. `--ink-faint`
 * composites to 3.32:1 over the dark surface and 2.56:1 over paper, because 40%
 * of cream over near-black and 40% of near-black over cream are not symmetric.
 * Asserting it unconditionally on paper would demand a token change, and token
 * values come from the design spec rather than from a check; asserting it
 * nowhere would let it become body copy unnoticed. So it is asserted on any
 * surface that has a page carrying an element the token is painted on — today
 * the glyph runs and the Helix diagram, all of which are dark — and the report
 * names the pairs it did not measure rather than passing over them in silence.
 */
export function classesPainting(css, token) {
  const classes = new Set();
  const uses = new RegExp(`var\\(\\s*${token}\\s*[,)]`);
  for (const rule of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
    if (!uses.test(rule[2])) continue;
    for (const c of rule[1].matchAll(/\.([\w-]+)/g)) classes.add(c[1]);
  }
  return classes;
}

/**
 * The surfaces, and the attribute a page carries to select each one.
 *
 * There is one. `paper` was a second entry here until MW-16: a cream surface
 * selected by `surface: paper` in a record's frontmatter, used by nine
 * documentation articles. The owner had those moved to dark — the docs were
 * the one part of the site that turned white under the reader — and then
 * removed the surface itself, so `layouts/shell-paper`, the
 * `[data-surface='paper']` token block and the frontmatter field are all gone.
 * Nothing can select it, so measuring it would be reporting on pixels that
 * cannot exist.
 *
 * The list is still a list, and `pagesOnSurface` still groups by the attribute,
 * because the shape is what makes the check honest: only surfaces a page in
 * `dist/` actually renders are measured, and the report names which those were.
 * A second surface added tomorrow starts being asserted on the run that ships
 * it, without this file changing shape.
 *
 * `@media print` is deliberately NOT here. Its contrast is a different question
 * — ink on real paper, not composited pixels — and this check measures what a
 * screen shows.
 */
const SURFACES = [{ name: 'dark', selector: ':root', attribute: 'dark' }];

/** The pages a given surface is actually painted on. */
const pagesOnSurface = (documents, attribute) =>
  documents.filter((html) => {
    const tag = /<html\b[^>]*>/i.exec(html);
    const surface = tag ? attrsOf(tag[0])['data-surface'] : undefined;
    return (surface || 'dark') === attribute;
  });

// ── the check ─────────────────────────────────────────────────────────────

export async function checkA11y(report) {
  if (!existsSync(ARTIFACTS.dist.path)) {
    report.skip('accessibility gates', ARTIFACTS.dist.rel, ARTIFACTS.dist.issue);
    return;
  }

  const { files } = indexDist();
  const pages = files.filter((f) => f.endsWith('.html'));
  if (!pages.length) {
    report.skip('accessibility gates', `${ARTIFACTS.dist.rel} (no HTML pages)`, ARTIFACTS.dist.issue);
    return;
  }

  const byKind = new Map();
  const documents = [];
  for (const file of pages) {
    const url = `/${file.replace(/index\.html$/, '').replace(/\.html$/, '')}`;
    const html = readFileSync(join(ARTIFACTS.dist.path, file), 'utf8');
    documents.push(html);
    for (const p of auditPage(url, html)) {
      if (!byKind.has(p.kind)) byKind.set(p.kind, []);
      byKind.get(p.kind).push(p.detail);
    }
  }

  /** One assertion per kind, so a failure names the defect rather than a count. */
  const ASSERTIONS = [
    ['lang', 'every page declares its own language'],
    ['viewport', 'every page is zoomable at its own width'],
    ['h1', 'every page has exactly one <h1>'],
    ['heading-skip', 'no page skips a heading level'],
    ['img-alt', 'every image carries an alt attribute'],
    ['iframe-title', 'every frame carries a title'],
    ['link-name', 'every link has an accessible name'],
    ['empty-link', 'no link is an empty target'],
    ['button-name', 'every button and disclosure has an accessible name'],
    ['control-label', 'every form control has a label'],
    ['hidden-focusable', 'nothing hidden from assistive technology keeps a tab stop'],
    ['tabindex', 'no positive tabindex reorders the tab sequence'],
    ['duplicate-id', 'ids are unique within a page'],
    ['dead-fragment', 'every in-page link points at an element that exists'],
    ['landmark', 'every page carries header, main and footer landmarks'],
    ['nav-name', 'every navigation landmark is named'],
    ['inline-handler', 'no control is built from an inline event handler'],
    ['table-header', 'every data table has header cells'],
  ];

  for (const [kind, label] of ASSERTIONS) {
    const found = byKind.get(kind) || [];
    if (!found.length) {
      report.pass(label, `${pages.length} pages`);
    } else {
      report.fail(
        label,
        `${found.length} on ${new Set(found.map((d) => d.split(':')[0])).size} page(s) — ` +
          found.slice(0, 3).join(' / ') +
          (found.length > 3 ? ` … and ${found.length - 3} more` : ''),
      );
    }
  }

  // ---- stylesheet-level gates --------------------------------------------
  /**
   * Every rule that ships, from both places rules ship.
   *
   * Astro emits a component's scoped `<style>` inline in the page when it is
   * small enough and into an external stylesheet when it is not, and which of
   * the two it picks is a bundler decision that can change between builds. A
   * check that read only `dist/**\/*.css` would have concluded that the glyph
   * runs are painted on no page at all — the rule that paints them is inline on
   * each of the 35 card pages.
   */
  const css = files.filter((f) => f.endsWith('.css')).map((f) => readFileSync(join(ARTIFACTS.dist.path, f), 'utf8'));
  const inline = documents.flatMap((html) => [...html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)].map((m) => m[1]));
  const allCss = [...css, ...inline].join('\n');

  if (!allCss.trim()) {
    report.skip('stylesheet accessibility gates', 'no CSS in dist/', 'MW-2');
    return;
  }

  /**
   * "focus is always a visible outline, never a shadow, never removed."
   * `outline: none` inside a rule that immediately supplies another outline is
   * a legitimate reset; one that does not is a removed focus ring.
   */
  const strippedFocus = [];
  for (const m of allCss.matchAll(/([^{}]*focus[^{}]*)\{([^}]*)\}/gi)) {
    const body = m[2];
    if (!/outline\s*:\s*(none|0)\b/i.test(body)) continue;
    if (/outline(-width|-style|-color)?\s*:\s*(?!none|0\b)/i.test(body.replace(/outline\s*:\s*(none|0)\b[^;]*;?/i, ''))) continue;
    strippedFocus.push(m[1].trim().slice(0, 60));
  }
  if (strippedFocus.length) {
    report.fail('the focus ring is never removed', `${strippedFocus.length} rule(s): ${strippedFocus.slice(0, 2).join(' / ')}`);
  } else {
    report.pass('the focus ring is never removed', `${css.length} stylesheets, ${inline.length} inline blocks`);
  }

  if (!/:focus-visible[^{]*\{[^}]*outline\s*:/i.test(allCss)) {
    report.fail('a visible focus ring is defined', 'no :focus-visible rule sets an outline');
  } else {
    report.pass('a visible focus ring is defined');
  }

  if (!/@media[^{]*prefers-reduced-motion\s*:\s*reduce/i.test(allCss)) {
    report.fail('prefers-reduced-motion is honoured', 'no (prefers-reduced-motion: reduce) block ships');
  } else {
    report.pass('prefers-reduced-motion is honoured');
  }

  /**
   * "long Spanish copy and unbroken URLs wrap safely" (MW-11). A legacy body
   * carries bare URLs, and a token wider than a 360px viewport pushes the whole
   * document sideways — the one overflow a media query cannot fix, because the
   * element is not the one that is too wide.
   */
  if (!/overflow-wrap\s*:\s*(break-word|anywhere)/i.test(allCss)) {
    report.fail('unbroken words and URLs are allowed to wrap', 'no overflow-wrap declaration ships');
  } else {
    report.pass('unbroken words and URLs are allowed to wrap');
  }

  /** Wide content gets its own scroll container instead of widening the page. */
  const scrollable = /(pre|table)[^{}]*\{[^}]*overflow-x\s*:\s*auto/i.test(allCss);
  if (!scrollable) {
    report.fail('wide content scrolls inside itself', 'no overflow-x:auto container for <pre>/<table>');
  } else {
    report.pass('wide content scrolls inside itself');
  }

  // ---- contrast ------------------------------------------------------------
  const failures = [];
  const measured = [];
  const notMeasured = [];
  const surfaces = SURFACES.map((s) => ({ ...s, pages: pagesOnSurface(documents, s.attribute) })).filter(
    (s) => s.pages.length,
  );

  for (const { name, selector, pages: surfacePages } of surfaces) {
    const resolve = resolveSurface(allCss, selector);
    if (!resolve) {
      failures.push(`${name}: no token block matching ${selector} in the built CSS`);
      continue;
    }
    for (const pair of CONTRAST_PAIRS) {
      if (pair.onlyWherePainted) {
        const classes = [...classesPainting(allCss, pair.fg)];
        const painted =
          classes.length > 0 &&
          surfacePages.some((html) => classes.some((c) => new RegExp(`class=["'][^"']*\\b${c}\\b`).test(html)));
        if (!painted) {
          notMeasured.push(`${pair.fg} on ${name} (painted on no ${name} page)`);
          continue;
        }
      }
      const fg = resolve(pair.fg);
      const bg = resolve(pair.bg);
      if (!fg || !bg) {
        failures.push(`${name}: cannot resolve ${!fg ? pair.fg : pair.bg}`);
        continue;
      }
      if (bg.alpha !== 1) {
        failures.push(`${name}: ${pair.bg} is not opaque — contrast against it is undefined`);
        continue;
      }
      const ratio = contrastRatio(composite(fg.rgb, fg.alpha, bg.rgb), bg.rgb);
      measured.push(ratio);
      if (ratio < pair.min) {
        failures.push(
          `${name}: ${pair.fg} on ${pair.bg} (${pair.what}) is ${ratio.toFixed(2)}:1, below ${pair.min}:1`,
        );
      }
    }
  }
  if (failures.length) {
    report.fail('text and focus meet WCAG 2.2 AA contrast', failures.slice(0, 3).join(' / '));
  } else {
    report.pass(
      'text and focus meet WCAG 2.2 AA contrast',
      `${measured.length} pairs on the ${surfaces.map((s) => `${s.name} (${s.pages.length})`).join(' and ')} ` +
        `surface${surfaces.length > 1 ? 's' : ''}, lowest ${Math.min(...measured).toFixed(2)}:1` +
        (notMeasured.length ? ` — not measured: ${notMeasured.join(', ')}` : ''),
    );
  }
}

if (process.argv[1] && process.argv[1].endsWith('verify-a11y.mjs')) {
  runStandalone('verify:a11y', checkA11y);
}
