#!/usr/bin/env node
/**
 * verify:actions — the movement budget from "Buttons v4 · the break", asserted.
 *
 * v4 gives a view a budget rather than a set of options:
 *
 *   "a view gets one stamp and one break, and everything else holds still …
 *    the collage only reads as a collage because most of the page is straight."
 *
 * That is the one rule in the action system that no component can enforce.
 * `ui/action` refuses every combination it can see — a stamp on a text button,
 * tape on a pigment field, a destructive control that breaks — but a component
 * knows nothing about its siblings, and nothing about the page it lands on. Two
 * page families can each spend a stamp perfectly correctly and produce a view
 * with two of them. The budget only exists at the level of a rendered page, so
 * it is checked against rendered pages.
 *
 * MEASURED AGAINST dist/, LIKE verify:a11y AND FOR THE SAME REASON. The classes
 * are what ship. A call site that spells `btn--stamp` by hand rather than going
 * through `ui/action` — `pages/[cardCode].astro` does exactly that, because it
 * needs `rel` — is invisible to any source-level check and completely visible
 * here. So are the two things a source check would have to guess at: whether a
 * conditional branch actually rendered, and whether two components landed on
 * one page.
 *
 * WHAT IT DOES NOT CHECK. Whether the RIGHT element got the stamp. v4 is honest
 * that this is editorial — *"picking the break is an editorial decision, like
 * choosing which word in a sentence gets the mark"* — and no build can have an
 * opinion about which control someone would point at while describing a screen.
 * What a build can do is hold the count to one and hold the pairings legal,
 * which is what stops the budget quietly becoming a default again.
 */

import { existsSync } from 'node:fs';
import { runStandalone } from './lib/report.mjs';
import { ARTIFACTS, indexDist, readDistFile } from './lib/artifacts.mjs';

/**
 * The classes the budget is written in.
 *
 * Kept as one table rather than as regexes scattered through the checks, so
 * that adding v4's two unbuilt gestures — `cut edge` and `slipped mark` — is
 * one line here and not an audit of this file.
 */
const BREAKS = ['pivot', 'tape', 'offset'];

/**
 * Every variant a control may carry, and which of them have a pigment field.
 *
 * BOTH LISTS EXIST BECAUSE ONE IS NOT ENOUGH. An earlier version asked only
 * "does this class list contain a filled variant", which answers yes for
 * `btn btn--primary btn--secondary btn--stamp` — a control with two variants,
 * where the later `.btn--secondary` rules strip the field the stamp needs and
 * the stamp is therefore forbidden. It passed. A check that reports on
 * hand-spelled markup has to notice markup that is malformed as well as markup
 * that is merely illegal, so the variant count is asserted first and every
 * other rule is derived from the single variant that survives it.
 */
const VARIANTS = ['primary', 'collect', 'secondary', 'text', 'destructive'];
const FILLED = ['primary', 'collect'];

/**
 * Every `class` attribute in a document, as an array of class lists.
 *
 * Deliberately not a parser, for the reason verify:a11y gives for its own tag
 * scanner: every page here is generated by Astro from normalised content, so
 * the tag soup a real parser exists to survive is not present, and a
 * dependency-free check is one that still runs in five years.
 */
function classListsOf(html) {
  const out = [];
  for (const m of html.matchAll(/\sclass\s*=\s*("([^"]*)"|'([^']*)')/g)) {
    const raw = m[2] ?? m[3] ?? '';
    const list = raw.split(/\s+/).filter(Boolean);
    if (list.includes('btn')) out.push(list);
  }
  return out;
}

/** Only real pages carry a budget. Feeds, sitemaps and the manifest do not. */
const isPage = (f) => f.endsWith('.html');

/**
 * The route-proof pages exist to prove that awkward URLs survive the build —
 * `route-proof/plain-space test.html` and friends. They are fixtures rather
 * than views, they are noindex, and holding them to an editorial budget would
 * be asserting a design rule about a test.
 */
const isFixture = (f) => f.startsWith('route-proof/');

export async function checkActions(report) {
  if (!existsSync(ARTIFACTS.dist.path)) {
    report.skip('the movement budget holds on every view', ARTIFACTS.dist.rel, ARTIFACTS.dist.issue);
    return;
  }

  const pages = indexDist().files.filter((f) => isPage(f) && !isFixture(f));
  if (pages.length === 0) {
    report.skip('the movement budget holds on every view', ARTIFACTS.dist.rel, ARTIFACTS.dist.issue);
    return;
  }

  const overspent = [];
  const illegal = [];
  let stampedViews = 0;
  let brokenViews = 0;
  let controls = 0;

  for (const page of pages) {
    const lists = classListsOf(readDistFile(page));
    controls += lists.length;

    let stamps = 0;
    let breaks = 0;

    for (const list of lists) {
      const isStamp = list.includes('btn--stamp');
      const gestures = BREAKS.filter((g) => list.includes(`btn--break-${g}`));
      const variants = VARIANTS.filter((v) => list.includes(`btn--${v}`));

      /* Counted before anything can bail out below. A malformed control still
         spends the view's budget — it is a stamp on the page whatever else is
         wrong with it — and a budget line that quietly under-counted would be
         the same class of lie this whole check exists to prevent. */
      if (isStamp) stamps += 1;
      breaks += gestures.length;

      /* A control with no variant or with two is malformed, and every pairing
         rule below reads a variant, so there is nothing meaningful to say about
         it until that is fixed. Reported and skipped rather than guessed at. */
      if (variants.length !== 1) {
        illegal.push(
          `${page}: a control carries ${variants.length} variants${
            variants.length ? ` (${variants.join(', ')})` : ''
          } — exactly one is required before any pairing can be judged`,
        );
        continue;
      }

      const [variant] = variants;
      const filled = FILLED.includes(variant);
      const destructive = variant === 'destructive';

      /* Everything below is a rule `ui/action` already refuses at build time.
         It is asserted again here because the built HTML is the only place a
         hand-spelled class list is visible, and `[cardCode]` proves those
         exist. A rule enforced in one of two doorways is not enforced. */
      if (isStamp && gestures.length) {
        illegal.push(`${page}: one control is both a stamp and a "${gestures[0]}" break`);
      }
      if (gestures.length > 1) {
        illegal.push(`${page}: one control carries ${gestures.length} breaks (${gestures.join(', ')})`);
      }
      if (isStamp && !filled) {
        illegal.push(`${page}: a stamp on an unfilled control — nothing to lift or cast a shadow`);
      }
      if (destructive && (isStamp || gestures.length)) {
        illegal.push(`${page}: a destructive control that ${isStamp ? 'stamps' : 'breaks'} — "semantics never break"`);
      }
      if (gestures.includes('tape') && filled) {
        illegal.push(`${page}: tape on a filled "${variant}" — two pastels in contact`);
      }
      if (gestures.includes('offset') && !filled) {
        illegal.push(`${page}: an offset print on an unfilled control — no block for the pigment to sit behind`);
      }
    }

    if (stamps > 1) overspent.push(`${page}: ${stamps} stamps`);
    if (breaks > 1) overspent.push(`${page}: ${breaks} breaks`);
    if (stamps === 1) stampedViews += 1;
    if (breaks === 1) brokenViews += 1;
  }

  if (overspent.length) {
    report.fail(
      'no view spends more than one stamp and one break',
      `${overspent.length} over budget — ${overspent.slice(0, 3).join(' / ')}`,
    );
  } else {
    report.pass(
      'no view spends more than one stamp and one break',
      `${pages.length} views, ${controls} controls — ${stampedViews} carry a stamp, ${brokenViews} carry a break`,
    );
  }

  if (illegal.length) {
    report.fail(
      'every stamp and break is a legal pairing',
      `${illegal.length} illegal — ${illegal.slice(0, 3).join(' / ')}`,
    );
  } else {
    report.pass(
      'every stamp and break is a legal pairing',
      'no stamp on an unfilled control, no tape on a field, nothing semantic that moves',
    );
  }

  /**
   * The budget is a ceiling, not a quota — a view with no stamp is correct, and
   * most of them are. But a build where NOTHING is ever stamped means the
   * signature gesture has silently left the site, which is the failure mode a
   * ceiling-only check cannot see. This reports rather than fails: it is a fact
   * about the build, and the number moving is what someone would want to know.
   */
  if (stampedViews === 0) {
    report.fail(
      'the stamp still exists somewhere in the build',
      'no view carries one — the signature gesture is not being spent anywhere',
    );
  } else {
    report.pass(
      'the stamp still exists somewhere in the build',
      `${stampedViews} of ${pages.length} views spend it`,
    );
  }
}

if (process.argv[1] && process.argv[1].endsWith('verify-actions.mjs')) {
  runStandalone('verify:actions', checkActions);
}
